spring:
  application:
    name: wise-task-gateway
grpc:
  service:
    graph:
      host: ${GRAPH_APP_NAME}
      port: ${GRAPH_GRPC_PORT}
    profile:
      host: ${PROFILE_APP_NAME}
      port: ${PROFILE_GRPC_PORT}
    plugin:
      host: ${PLUGIN_APP_NAME}
      port: ${PLUGIN_GRPC_PORT}
    task:
      host: ${TASK_APP_NAME}
      port: ${TASK_GRPC_PORT}
    statistics:
      host: ${EVENT_APP_NAME}
      port: ${EVENT_GRPC_PORT}
server:
  port: ${GATEWAY_PORT}
security:
  jwt:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
    expiration: ${JWT_EXPIRATION_SEC}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: "*"
    allow-credentials: ${CORS_ALLOWED_CREDENTIALS}
    max-age: ${CORS_MAX_AGE}

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    ru.leti.wise.task.gateway: ${LOGGING_LEVEL}
    org.springframework.web: ${LOGGING_LEVEL}
    org.springframework.security: ${LOGGING_LEVEL}


management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://${TEMPO_HOST}:${TEMPO_PORT}/api/v2/spans

