spring:
  application:
    name: wise-task-gateway

grpc:
  service:
    graph:
      host: localhost
      port: ${GRAPH_GRPC_PORT}
    profile:
      host: localhost
      port: ${PROFILE_GRPC_PORT}
    plugin:
      host: localhost
      port: ${PLUGIN_GRPC_PORT}
    task:
      host: localhost
      port: ${TASK_GRPC_PORT}
    statistics:
      host: localhost
      port: ${EVENT_GRPC_PORT}
server:
  port: ${GATEWAY_PORT}

security:
  jwt:
    public-key: file:src/main/resources/certs/public.pem

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: "*"
    allow-credentials: ${CORS_ALLOWED_CREDENTIALS}
    max-age: ${CORS_MAX_AGE}

logging:
  level:
    ru.leti.wise.task.gateway: ${LOGGING_LEVEL}
    org.springframework.security: ${LOGGING_LEVEL}


management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://${TEMPO_HOST:localhost}:${TEMPO_PORT:4318}/v1/traces
  otlp:
    metrics:
      export:
        enabled: false # prometheus will do it
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
