CREATE DATABASE wise_task_profile;
CREATE DATABASE wise_task_plugin;
CREATE DATABASE wise_task_task;

CREATE USER wise_task_profile WITH PASSWORD 'wise_task_profile';
CREATE USER wise_task_plugin WITH PASSWORD 'wise_task_plugin';
CREATE USER wise_task_task WITH PASSWORD 'wise_task_task';

GRANT ALL PRIVILEGES ON DATABASE wise_task_profile TO wise_task_profile;
GRANT USAGE, CREATE ON SCHEMA public TO wise_task_profile;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wise_task_profile;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO wise_task_profile;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wise_task_profile;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO wise_task_profile;

GRANT ALL PRIVILEGES ON DATABASE wise_task_plugin TO wise_task_plugin;
GRANT USAGE, CREATE ON SCHEMA public TO wise_task_plugin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wise_task_plugin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO wise_task_plugin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wise_task_plugin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO wise_task_plugin;

GRANT ALL PRIVILEGES ON DATABASE wise_task_task TO wise_task_task;
GRANT USAGE, CREATE ON SCHEMA public TO wise_task_task;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wise_task_task;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO wise_task_task;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wise_task_task;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO wise_task_task;

